"""
Generate ILLUSTRATIVE geo data for `data/geo/` so the live map has something to
draw before real boundary data arrives.

    python tools/make_demo_geo.py            # write the files
    python tools/make_demo_geo.py --stdout   # print, change nothing

WHAT THIS IS NOT
----------------
These are not Cabadbaran City's real barangay boundaries and the MRF pins are
not the real facilities. Nothing here was surveyed. Every shape is invented by
this script from a hand-placed centre point, chosen so the map reads as a
plausible city rather than a blank frame during a demo.

Both output files therefore keep `"_placeholder": true`. The app treats that
flag as "this data is illustrative": `geo_service` still loads and draws the
geometry, `status()` still reports it as not-real, and the map shows a caption
saying so. Nothing in the system ever claims this is survey data.

WHAT IT IS BASED ON
-------------------
Three things about the real city, and nothing more:

  * the city centre, 9.1226 / 125.5344 (`Config.MAP_DEFAULT_CENTER`)
  * Butuan Bay lies to the west, its shore running roughly NNW-SSE, so the
    territory extends inland to the east
  * the twelve Poblacion barangays form a compact urban core; the other
    nineteen are larger and spread around it

Barangay centres below are placed by rough compass position only. A barangay
sits in about the right direction from the centre at about the right distance;
it does not sit on its real footprint.

REPLACING IT WITH REAL DATA
---------------------------
Overwrite the two files with real GeoJSON and drop the `_placeholder` flag.
No code changes -- `geo_service` reads whatever is on disk, and the mtime cache
picks up the swap without a restart. See docs/DATA_REQUIREMENTS.md for the
exact schema, and the OpenStreetMap route if you want real shapes without a
survey.
"""

import argparse
import json
import math
import random
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from config import Config                                   # noqa: E402
from services import geo_service, storage                    # noqa: E402

PLACEHOLDER_NOTE = (
    "ILLUSTRATIVE DEMO DATA -- generated by tools/make_demo_geo.py, not "
    "surveyed. Shapes and MRF pins are approximations placed by compass "
    "direction from the city centre; they are not the real barangay "
    "boundaries. Replace with real GeoJSON and delete the _placeholder flag. "
    "See docs/DATA_REQUIREMENTS.md."
)

# The same warning, for a run that had the real barangay coordinates to work
# from. Weaker, because the positions are now right to within a barangay -- but
# still a warning, because "in the right barangay" is not "at the facility".
DERIVED_NOTE = (
    "PARTLY REAL DATA -- barangay positions are the published coordinates in "
    "data/geo/barangay_centres.json, so every pin is in the right barangay. "
    "The MRF pins are NOT surveyed: each is placed a short distance from its "
    "barangay's centre because the facility's own location is not yet known. "
    "Boundaries remain generated shapes, not surveyed ones. Replace the MRF "
    "coordinates with GPS readings taken at each facility and delete the "
    "_placeholder flag. See docs/DATA_REQUIREMENTS.md."
)

# Where tools/fetch_barangay_centres.py leaves the real coordinates.
CENTRES_FILE = "barangay_centres.json"

# Where tools/import_mrf_survey.py leaves coordinates measured at the facility
# itself. These outrank everything this script can work out on its own.
SURVEY_FILE = "mrf_surveyed.json"

# The note for a run where some facilities are surveyed and some are not. The
# count is filled in, because "partly surveyed" is useless without knowing
# which part -- and every MRF row carries its own `surveyed` flag for anything
# that needs to tell them apart one at a time.
MIXED_NOTE = (
    "PARTLY SURVEYED -- {surveyed} of {total} MRF coordinates were measured at "
    "the facility and are exact. The remaining {derived} are NOT surveyed: each "
    "is placed a short distance from its barangay's published centre, which "
    "puts it in the right barangay but not at the building. Every MRF entry "
    "carries a `surveyed` flag saying which it is. Boundaries remain generated "
    "shapes. Add surveyed coordinates with tools/import_mrf_survey.py. "
    "See docs/DATA_REQUIREMENTS.md."
)

SURVEYED_NOTE = (
    "MRF COORDINATES ARE SURVEYED -- all {total} were measured at the facility "
    "and are used exactly as supplied; every MRF entry carries `surveyed`: "
    "true. BOUNDARIES ARE NOT: the barangay outlines in barangay_zones.geojson "
    "are still generated shapes drawn around each barangay's published centre, "
    "so they decide where the map opens and nothing more. Re-import or correct "
    "a facility with tools/import_mrf_survey.py, or from the City Hall Admin "
    "MRF page. See docs/DATA_REQUIREMENTS.md."
)

# Hand-placed approximate centres, (lat, lng). Rural barangays are positioned
# by rough compass direction from the Poblacion; the twelve Poblacion barangays
# are laid out on a compact grid further down rather than listed here.
RURAL_CENTRES = {
    # north, along and behind the coast
    "Sanghan":      (9.1950, 125.5290),
    "Puting Bato":  (9.1775, 125.5420),
    "Bay-ang":      (9.1660, 125.5265),
    "Antonio Luna": (9.1545, 125.5210),
    # north-east, inland toward the Diwata range
    "Katugasan":    (9.1840, 125.5760),
    "Tolosa":       (9.1690, 125.6120),
    # east of the Poblacion
    "Calibunan":    (9.1420, 125.5640),
    "Mahaba":       (9.1460, 125.6160),
    "Comagascas":   (9.1290, 125.5790),
    "Soriano":      (9.1215, 125.6390),
    "Del Pilar":    (9.1090, 125.6060),
    # south-east
    "Caasinan":     (9.0955, 125.5860),
    "Cabinet":      (9.0805, 125.6210),
    # south
    "Mabini":       (9.1040, 125.5460),
    "La Union":     (9.0895, 125.5320),
    "Kauswagan":    (9.0745, 125.5495),
    "Calamba":      (9.0615, 125.5290),
    # west and south-west, near the shore
    "Bayabas":      (9.1055, 125.5205),
    "Concepcion":   (9.0870, 125.5235),
}

# The Poblacion core: a 3-column, 4-row grid centred on the city centre.
# ~0.008 deg is roughly 900 m, so the whole core spans about 2.5 x 3 km.
POBLACION_ORIGIN = (9.1226, 125.5344)
POBLACION_COL_STEP = 0.0084
POBLACION_ROW_STEP = 0.0076
POBLACION_COLS = 3

# Polygon shaping.
VERTEX_COUNT = (7, 9)      # sides per barangay, chosen per barangay
RADIUS_FRACTION = 0.46     # of the distance to the nearest neighbouring centre
JITTER = 0.22              # +/- fraction of the radius, per vertex
SHORE_MARGIN = 0.0022      # keep land this far east of the waterline

# How far an MRF pin sits from its barangay's centre. About 90 m: far enough
# that the pin is not claiming to BE the barangay's centre point, close enough
# that it is unmistakably in the right place. It is a stand-in for a survey,
# and it should look like one.
MRF_OFFSET = 0.0008


def shore_lng(lat: float) -> float:
    """
    A crude Butuan Bay waterline: NNW-SSE, passing 125.518 at the city centre's
    latitude. Used only to stop generated polygons and MRF pins landing in the
    sea, which is the one error that makes an approximate map look broken
    rather than approximate.
    """
    return 125.518 + (9.12 - lat) * 0.18


def clamp_to_land(lat: float, lng: float) -> tuple[float, float]:
    return lat, max(lng, shore_lng(lat) + SHORE_MARGIN)


def poblacion_centre(index: int) -> tuple[float, float]:
    """Grid slot for Poblacion N (1-based), filling left-to-right, top-down."""
    row, col = divmod(index - 1, POBLACION_COLS)
    lat = POBLACION_ORIGIN[0] + (1.5 - row) * POBLACION_ROW_STEP
    lng = POBLACION_ORIGIN[1] + (col - 1) * POBLACION_COL_STEP
    return lat, lng


def surveyed_mrfs() -> dict[str, tuple[float, float]]:
    """
    Facilities somebody has actually stood at, by barangay id.

    Empty when nothing has been surveyed yet, which is the state this project
    started in and the one the rest of the script still has to work in.
    """
    path = Path(Config.GEO_DIR) / SURVEY_FILE
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {row["barangay_id"]: (row["lat"], row["lng"])
            for row in data.get("surveyed", [])
            if row.get("barangay_id") and row.get("lat") is not None}


def real_centres() -> dict[str, tuple[float, float]]:
    """
    The published barangay coordinates, if they have been fetched.

    Returns an empty dict when the file is absent, which is what makes this
    optional: the script still runs on a fresh clone with nothing but its own
    compass guesses, and quietly gets far better when the real data appears.
    """
    path = Path(Config.GEO_DIR) / CENTRES_FILE
    if not path.exists():
        return {}
    try:
        data = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return {}
    return {row["barangay_id"]: (row["lat"], row["lng"])
            for row in data.get("centres", [])
            if row.get("barangay_id") and row.get("lat") is not None}


def centres(barangays: list[dict]) -> dict[str, tuple[float, float]]:
    """
    One centre per barangay id, real ones first.

    A real coordinate is used exactly as published -- no shoreline clamping,
    no adjustment. The clamp exists to stop *invented* points drifting into
    Butuan Bay; applying it to a surveyed figure would be the script overruling
    the truth with its own rough model of where the coast is.
    """
    out: dict[str, tuple[float, float]] = dict(real_centres())
    if out:
        print(f"  using {len(out)} real barangay coordinates from {CENTRES_FILE}")

    unplaced = []
    for row in barangays:
        if row["id"] in out:
            continue
        name = row.get("name") or ""
        if name.startswith("Poblacion"):
            try:
                out[row["id"]] = poblacion_centre(int(name.split()[-1]))
                continue
            except (ValueError, IndexError):
                pass
        if name in RURAL_CENTRES:
            out[row["id"]] = RURAL_CENTRES[name]
        else:
            unplaced.append(row)

    # A barangay the script has never heard of still gets a spot, on a ring
    # outside everything else, so a renamed or added barangay is visible and
    # obviously provisional instead of silently missing.
    for i, row in enumerate(unplaced):
        angle = 2 * math.pi * i / max(1, len(unplaced))
        out[row["id"]] = clamp_to_land(
            POBLACION_ORIGIN[0] + 0.085 * math.sin(angle),
            POBLACION_ORIGIN[1] + 0.085 * math.cos(angle),
        )
    if unplaced:
        print(f"  note: {len(unplaced)} barangay(s) not in RURAL_CENTRES, "
              f"placed on the outer ring: "
              f"{', '.join(r.get('name', '?') for r in unplaced)}")
    return out


def nearest_gap(point: tuple[float, float],
                others: list[tuple[float, float]]) -> float:
    """Distance to the closest other centre, in degrees."""
    gaps = [math.hypot(point[0] - o[0], point[1] - o[1])
            for o in others if o != point]
    return min(gaps) if gaps else 0.02


def polygon(barangay_id: str, centre: tuple[float, float],
            radius: float) -> list[list[float]]:
    """
    An irregular closed ring around `centre`, seeded on the barangay id so the
    same input always produces the same shape -- regenerating the files does
    not reshuffle the map.
    """
    rng = random.Random(barangay_id)
    sides = rng.randint(*VERTEX_COUNT)
    start = rng.random() * 2 * math.pi

    ring = []
    for i in range(sides):
        angle = start + 2 * math.pi * i / sides
        reach = radius * (1 + rng.uniform(-JITTER, JITTER))
        lat, lng = clamp_to_land(centre[0] + reach * math.sin(angle),
                                 centre[1] + reach * math.cos(angle))
        ring.append([round(lng, 6), round(lat, 6)])   # GeoJSON is [lng, lat]

    ring.append(ring[0])                              # close the ring
    return ring


def build(barangays: list[dict]) -> tuple[dict, list]:
    placed = centres(barangays)
    all_points = list(placed.values())

    # Which warning the files carry depends on what this run had to work from.
    # Claiming pins were placed "by compass direction from the city centre"
    # would understate real data as badly as the reverse would overstate it,
    # and once some facilities are surveyed the note has to say how many --
    # "approximate" covering a mix of exact and invented figures is the kind
    # of caveat that gets ignored precisely because it is always there.
    surveyed = surveyed_mrfs()
    if surveyed and len(surveyed) >= len(barangays):
        note = SURVEYED_NOTE.format(total=len(barangays))
    elif surveyed:
        note = MIXED_NOTE.format(surveyed=len(surveyed), total=len(barangays),
                                 derived=len(barangays) - len(surveyed))
    elif real_centres():
        note = DERIVED_NOTE
    else:
        note = PLACEHOLDER_NOTE

    zones = {
        "type": "FeatureCollection",
        "_placeholder": True,
        "_note": note,
        "features": [],
    }
    # Only a placeholder while some facility is still positioned by script.
    # Once the city has surveyed all of them the file holds measured
    # geography and says so, so the app stops warning about it.
    mrfs: list = [{"_placeholder": len(surveyed) < len(barangays),
                   "_placeholder_note": note}]

    for row in sorted(barangays, key=lambda b: b.get("number") or 0):
        bid, name = row["id"], row.get("name")
        centre = placed[bid]
        radius = max(0.0028, RADIUS_FRACTION * nearest_gap(centre, all_points))

        zones["features"].append({
            "type": "Feature",
            "properties": {
                "barangay_id": bid,
                "name": name,
                "zone_group": geo_service.zone_group_for(
                    row.get("number") or 0)["key"],
            },
            "geometry": {"type": "Polygon",
                         "coordinates": [polygon(bid, centre, radius)]},
        })

        # A surveyed facility is used exactly as measured -- no nudging, no
        # clamping. Everything this script knows about where barangays lie is
        # rougher than somebody standing at the gate with a GPS.
        if bid in surveyed:
            lat, lng = surveyed[bid]
            is_surveyed = True
        else:
            # Otherwise: a short, deterministic step off the barangay centre,
            # so the pin is in the right barangay without pretending to be the
            # barangay's own centre point.
            rng = random.Random(f"mrf:{bid}")
            angle = rng.random() * 2 * math.pi
            lat, lng = clamp_to_land(centre[0] + MRF_OFFSET * math.sin(angle),
                                     centre[1] + MRF_OFFSET * math.cos(angle))
            is_surveyed = False

        mrfs.append({
            "barangay_id": bid,
            "name": f"{name} MRF",
            "lat": round(lat, 6),
            "lng": round(lng, 6),
            # Per-facility, because the file as a whole is now neither surveyed
            # nor invented. Anything measuring distances has to be able to ask
            # this of one pin at a time.
            "surveyed": is_surveyed,
        })

    return zones, mrfs


def write(barangays: list[dict], announce=print) -> list[Path]:
    """
    Build both files and write them to `data/geo/`, returning what was written.

    Split out of main() so app.py can call it on a first local run: the map is
    unusable without geometry, and a page that cannot draw a barangay cannot
    zoom to one either. `announce` is print for the CLI and a no-op for the
    startup path, which does its own logging.
    """
    zones, mrfs = build(barangays)

    geo_dir = Path(Config.GEO_DIR)
    geo_dir.mkdir(parents=True, exist_ok=True)
    written = []
    for filename, payload in ((geo_service.ZONES_FILE, zones),
                              (geo_service.MRFS_FILE, mrfs)):
        target = geo_dir / filename
        target.write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")
        announce(f"  wrote {target}")
        written.append(target)

    # geo_service caches on mtime; drop it so the next request sees the new
    # geometry rather than the stub it loaded a moment ago.
    geo_service.clear_cache()
    return written


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true",
                        help="print the files instead of writing them")
    args = parser.parse_args()

    storage.bootstrap()
    barangays = storage.read("barangays")
    if not barangays:
        print("No barangays in the store. Run `python seed.py` first.")
        return 1

    if args.stdout:
        zones, mrfs = build(barangays)
        print(json.dumps(zones, indent=2))
        print(json.dumps(mrfs, indent=2))
        return 0

    write(barangays)
    status = geo_service.status()
    print(f"\n  zones: {status['zones']['loaded']}/{status['zones']['total']} "
          f"with geometry")
    print(f"  mrfs:  {status['mrfs']['loaded']}/{status['mrfs']['total']} "
          f"located")
    if status['mrfs']['total'] and not status['mrfs']['placeholder']:
        print("\n  mrf_locations.json is real data now -- every facility is "
              "surveyed, so it is no longer marked _placeholder.")
        print("  barangay_zones.geojson stays marked _placeholder: the "
              "outlines are still generated shapes.")
    else:
        print("\n  Both files stay marked _placeholder -- the map draws them but "
              "labels them illustrative.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
